config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/activity/show/:id' => 'activities#show', :as => :show_activity
  get '/activity/:id/edit' => 'activities#edit', :as => :edit_activity
  patch '/activity/:id/update' => 'activities#update', :as => :update_activity
  delete '/activity/:id/delete' => 'activities#destroy', :as => :delete_activity
  get '/activity/new(/:id)' => 'activities#new', :as => :new_activity
  post '/activity/create' => 'activities#create', :as => :create_activity
  get '/activity/profile' => 'activities#index', :as => :profile
  get '/activity/stopwatch' => 'activities#timer', :as => :timer
  get '/activities' => 'activities#activities', :as => :activities

  get '/about' => 'pages#about'


end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :exercises
  has_many :users, through: :exercises
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :user
  belongs_to :activity

  validates_associated :activity
  validates :activity_id, :status, :duration, :date, :mood, presence: true
  validates :activity_id, numericality: { only_integer: true } 
  validates :status, :duration, length: { minimum: 3, maximum: 20 }
  validates :mood,  length: { minimum: 3, maximum: 20 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  
  has_many :exercises
  has_many :activities, through: :exercises
  
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!

  def index
    @exercises = Exercise.where(user_id: current_user.id)
    @activities = Activity.all
    @user_activities = current_user.activities

    @activity_count = @user_activities.count
    @last = Exercise.where(user_id: current_user.id).order(date: :asc).last
    @done = Exercise.where(user_id: current_user.id).where(status: 'Complete').count
  end

  def activities
    @activities = Activity.all
  end

  def new
    @activities = Activity.all
    #render plain: @activities.inspect
    @exercise = Exercise.new
    if defined?(params[:id])
      @exercise.activity_id = params[:id]
    end
  end

  def create
    #render plain: exercise_params.inspect
    @exercise = Exercise.new(exercise_params)
    @exercise.user_id = current_user.id;
    if @exercise.save
      flash[:alert] = "Your activity was successfully added"
      redirect_to show_activity_path(@exercise)
    else
      render 'new'
    end
  end


  def edit
    @activities = Activity.all
    @exercise = Exercise.find(params[:id])
    #render plain: @exercise.inspect
  end

  def update
    @exercise = Exercise.find(params[:id])
    if @exercise.update(exercise_params)
      flash[:alert] = "Your Activity has been updated"
      redirect_to profile_path
    else
      render 'edit'
    end 
  end

  def show
    @exercise = Exercise.where(user_id: current_user.id).find(params[:id])
    @activity = current_user.activities.find(@exercise.activity_id)
  end

  def destroy
    @exercise = Exercise.find(params[:id])
    #render plain: @exercise.inspect
    @exercise.delete
    flash[:alert] = "Your activity has been deleted"
    redirect_to profile_path
  end

  def timer
  end

  private
  def exercise_params 
    params.require(:exercise).permit(:activity_id, :status, :duration, :date, :mood, :note)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    profile_path
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def about
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    profile_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/activities.html.erb
<section>
  <div class="jumbotron jumbotron-fluid bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 text-center text-white montserrat pt-3 pb-3">
          <h1 class="display-3 font-weight-bold">Get Started Today!</h1>
          <h4>Checkout all the exercises we offer</h4>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container-fluid pb-8">
    <div class="d-flex justify-content-center flex-wrap">
      <% @activities.each do |activity| %>
      <div class="card m-3" style="max-width:250px; min-width:220px;">
      <a href="/activity/new/<%= activity.id %>" class="m-auto">
          <img src="<%= activity.image %>" class="pt-3 pb-4" style="width:100px;border-bottom:1px solid gray;">
        </a>
        <div class="card-body pt-4 px-3">
          <h5 class="card-title"><%= activity.title %></h5>
          <h6 class="card-subtitle mb-2 text-muted small">Duration: <%= activity.duration %>  Difficulty: <%= activity.difficulty %>/5</h6>
          <p class="card-text txt-14"><%= activity.description %></p>
          <p class="text-center">
            <%= link_to 'Start', new_activity_path(activity), class: "card-link" %>
          </p>
        </div>
      </div>

      <% end %>

    </div>
  </div>
</section>

app/views/activities/edit.html.erb
<section>
  <div class="jumbotron jumbotron-fluid bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 text-left text-white montserrat py-1">
          <h1 class="display-4 font-weight-bold">Edit My Activity</h1>
        </div>
      </div>
    </div>
  </div>
</section>

<%= render 'activities/partials/error_msg'%>

<section>
  <div class="container pb-8">
    <div class="row">
      <div class="col-12 pt-4">
        <p class="text-right">
          <%= link_to 'Back to Profile', profile_path, class: "btn-link" %>
        </p>
        <%= form_for @exercise, url: {action: "update"} do |f| %>
        <div class="form-group">
          <span class="">*</span>
          <%= f.label :activity_id  %>
          <%= f.collection_select :activity_id, Activity.order(:id), :id, :title, {:include_blank => 'Pick an activity'}, {:class => "form-control", :required => true} %>
        </div>

        <div class="form-group">
          <span class="">*</span>
          <%= f.label :status %>
          <%= f.select :status, options_for_select([['complete', 'Complete'], ['incomplete', 'Incomplete']], @exercise.status), {:include_blank => "Select a status"}, {:class => "form-control", required: true} %>
        </div>


        <div class="form-group">
          <span class="">*</span>
          <%= f.label :date %>
          <%= f.date_field :date, class: "form-control", required: true %>
        </div>

        <p>
        <span style="color:red;">*</span>
          Duration
        </p>

        <div class="form-inline pb-2">
         <div class="form-group">
           <input type="number" id="hrs"  max="99" min="0" class="howLong form-control mb-2 mr-sm-2" value="00">
           <label class="mr-3">Hrs</label>
           <input id="mins" type="number" max="60" min="0" class="howLong form-control mb-2 mr-sm-2" id="hour" value="00">
           <label class="mr-3">Mins</label>
           <input id="secs" type="number" max="60" min="0" class=" howLong form-control mb-2 mr-sm-2" id="hour" value="00">
           <label>Secs</label>
         </div>
       </div>

       <div class="form-group d-none">
         <span class="">*</span>
         <%= f.label :duration %>
         <%= f.text_field :duration, class: "form-control", required: true %>
       </div>

       <div class="form-group">
         <span class="">*</span>
         <%= f.label :mood %>
         <%= f.select :mood, options_for_select([['okay', 'Okay'], ['good', 'Good'], ['energized', 'Energized'], ['bad', 'Bad'], ['lazy', 'Lazy'], ['sore', 'Sore']], @exercise.mood), {:include_blank => "Select your mood"}, {:class => "form-control", required: true} %>
       </div>

       <div class="form-group">
        <%= f.submit class: "btn btn-success px-3" %>
      </div>

      <% end %>

    </div>
  </div>
</div>
</section>

app/views/activities/index.html.erb
<section>
  <div class="jumbotron jumbotron-fluid bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 text-left text-white montserrat py-1">
          <h1 class="display-4 font-weight-bold">My Profile</h1>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row">
      <div class="col-12 text-center py-4">
        <h4 class="font-weight-bold">Stats</h4>
      </div>
      <div class="col-lg-4 col-md-6 col-12">
        <div class="card bg-light mb-3">
          <div class="card-header">Completed Activities</div>
          <div class="card-body">
            <h5 class="card-title"><img src="https://png.icons8.com/color/100/000000/triceps.png" style="width:65px;"> <span class="float-right txt-30"><%= @done %></span></h5>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-12">
        <div class="card bg-light mb-3">
          <div class="card-header">Total Activities</div>
          <div class="card-body">
            <h5 class="card-title"><img src="https://png.icons8.com/color/100/000000/sports-mode.png" style="width:65px;"> <span class="float-right txt-30"><%= @activity_count %></span></h5>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-12">
        <div class="card bg-light mb-3">
          <div class="card-header">Last Workout</div>
          <div class="card-body">
            <h5 class="card-title"><img src="https://png.icons8.com/color/100/000000/calendar.png" style="width:65px;"> <span class="float-right txt-30"><%= @last ? @last.date.to_time.strftime('%d %b, %Y') : 0 %></span></h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<section>
  <div class="container-fluid pb-10">
    <div class="row">
      <div class="col-12 text-center">
        <h4 class="font-weight-bold pb-4 pt-6">All My Activities</h4>
      </div>
    </div>
    <div class="d-flex justify-content-center flex-wrap">
      <% @exercises.each do |exercise| %>
      <% @activities.each do |activity| %>
      <% if exercise.activity_id  == activity.id %>
      <div class="card m-3" style="max-width:250px; min-width:220px;">
        <img src="<%= activity.image %>" class="m-auto pt-3 pb-4" style="width:100px;border-bottom:1px solid gray;">
        <div class="card-body pt-4 px-3">
          <h5 class="card-title"><%= activity.title %></h5>
          <h6 class="card-subtitle mb-2 text-muted small">
          Duration: <%= exercise.duration %>  Mood: <%= exercise.mood %>
            <br>
            Status: <%= exercise.status %>
          </h6>
          <%= link_to 'Edit', edit_activity_path(exercise), class: "card-link" %>
          <a class="card-link text-danger pointer" data-toggle="modal" data-target="#exampleModal" data-delete='<%= link_to 'Yes, Delete', delete_activity_path(exercise), method: :delete, class: "btn btn-danger"%>'>Delete</a>
        </div>
      </div>
      <% end %>
      <% end %>
      <% end %>
    </div>
  </div>
</section>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">Alert</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <p class="modal-btn m-0"></p>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->

app/views/activities/new.html.erb
<section>
  <div class="jumbotron jumbotron-fluid bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 text-left text-white montserrat py-1">
          <h1 id="pageTitle" class="display-4 font-weight-bold text-center">
          <% @activities.each do |activity| %>
            <% if activity.id == @exercise.activity_id %>
              <%= activity.title %>
            <% end %>
          <% end %>
          </h1>
        </div>
      </div>
    </div>
  </div>
</section>

<%= render 'activities/partials/error_msg'%>


<section>
  <div class="container pb-8 mb-8">
    <div class="row" style="overflow:hidden;">
      <div id="timerContainer" style="position:relative;" class="col-12 pt-4 text-center">
        <div id="intimerContainer">
          <p class="h1 pb-3 montserrat font-weight-bold">Start your activity!</p>
          <div id="chronoExample">
            <div id="time" class="values txt-50 txt-md-50 pb-3">00:00:00:00</div>
            <div>
              <button class="startButton btn btn-success">Start</button>
              <button class="stopButton btn btn-danger" style="display: none;">Done!</button>
              <button class="pauseButton btn btn-primary">Pause</button>
            </div>
          </div>
        </div>
        <div id="completeContainer" style="display: none;">
          <p class="h2 pb-3 pt-3">Did you complete your activity?</p>
          <button id="Complete" class="pauseButton btn btn-primary" onclick="getTimer(this)">Yes</button>
          <button id="Incomplete" class="btn btn-danger" onclick="getTimer(this)">No</button>
        </div>

      </div>

      <div id="emojiContainer" class="col-12 pt-4 text-center px-0" style="position:relative;left:100%;display:none;">
        <p class="h2 pb-2"> How do you feel about your workout?</p>
        <div class="d-flex justify-content-around flex-wrap">
          <div class="m-4" id="Energized" onclick="getMood(this)">
            <img src="https://png.icons8.com/color/96/000000/lol.png" class="d-block img-fluid pb-2" style="width:130px;">
            <button class="btn btn-primary btn-sm">Energized</button>
          </div>
          <div class="m-4" id="Good" onclick="getMood(this)">
            <img src="https://png.icons8.com/color/96/000000/happy.png" class="d-block img-fluid pb-2" style="width:130px;">
            <button class="btn btn-primary btn-sm">Good</button>
          </div>
          <div class="m-4" id="Okay" onclick="getMood(this)">
            <img src="https://png.icons8.com/color/96/000000/neutral-emoticon.png" class="d-block img-fluid pb-2" style="width:130px;">
            <button class="btn btn-primary btn-sm">Okay</button>
          </div>
          <div class="m-4" id="Bad" onclick="getMood(this)">
            <img src="https://png.icons8.com/color/96/000000/sad.png" class="d-block img-fluid pb-2" style="width:130px;">
            <button class="btn btn-danger btn-sm">Bad</button>
          </div>
          <div class="m-4" id="Lazy" onclick="getMood(this)">
            <img src="https://png.icons8.com/color/96/000000/bored.png" class="d-block img-fluid pb-2" style="width:130px;">
            <button class="btn btn-danger btn-sm">Lazy</button>
          </div>
          <div class="m-4" id="Sore" onclick="getMood(this)">
            <img src="https://png.icons8.com/dotty/80/000000/bored.png" class="d-block img-fluid pb-2" style="width:130px;">
            <button class="btn btn-danger btn-sm">Sore</button>
          </div>

        </div>
      </div>
    </div>
  </section>

  <section class="d-none">
    <div class="container pb-8">
      <div class="row">
        <div class="col-12 pt-4">
          <p class="text-right">
            <%= link_to 'Back to Profile', profile_path, class: "btn-link" %>
            <%= link_to 'View Activities', activities_path, class: "btn-link" %>
          </p>
          <%= form_for @exercise, url: {action: "create"} do |f| %>
          <div class="form-group">
            <span class="">*</span>
            <%= f.label :activity_id  %>
            <%= f.collection_select :activity_id, Activity.order(:id), :id, :title, {:include_blank => 'Pick an activity'}, {:class => "form-control", :required => true} %>
          </div>

          <div class="form-group">
           <span class="">*</span>
           <%= f.label :status %>
           <%= f.select :status, options_for_select([['complete', 'Complete'], ['incomplete', 'Incomplete']], "Incomplete"), {}, {:class => "form-control", required: true} %>
         </div>

         <div class="form-group">
           <span class="">*</span>
           <%= f.label :date %>
           <%= f.date_field :date, class: "form-control", required: true, id: "date" %>
         </div>

         <div class="form-group">
           <span class="">*</span>
           <%= f.label :duration %>
           <%= f.text_field :duration, class: "form-control", required: true, value: "00:00:00", id: "duration" %>
         </div>

         <div class="form-group">
           <span class="">*</span>
           <%= f.label :mood %>
           <%= f.select :mood, options_for_select([['okay', 'Okay'], ['good', 'Good'], ['energized', 'Energized'], ['bad', 'Bad'], ['lazy', 'Lazy'], ['sore', 'Sore']], "Okay"), {}, {:class => "form-control", required: true, id: "mood"} %>
         </div>

         <div class="form-group">
          <%= f.submit class: "btn btn-success px-3" %>
        </div>

        <% end %>

      </div>
    </div>
  </div>
</section>

app/views/activities/partials/_error_msg.html.erb
<% if @exercise.errors.any? %>
<section>
  <div class="container">
    <div class="row">
      <div class="col-12 bg-danger">
       <div class="text-white text-center pt-2">
          <% @exercise.errors.full_messages.each do |e| %>
          <p class="alert"><%= e %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<% end %>

app/views/activities/show.html.erb
<section>
  <div class="jumbotron jumbotron-fluid bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 text-left text-white montserrat py-1">
          <h1 class="display-4 font-weight-bold">Show Activity</h1>
        </div>
      </div>
    </div>
  </div>
</section>


<section>
  <div class="container pb-8">
    <div class="row">
      <div class="col-12 pt-4 text-center">
       <img src="<%= @activity.image  %>" class="m-auto pt-3 pb-4" style="width:100px;border-bottom:1px solid gray;">
       <h5 class="card-title pt-4"><%= @activity.title %></h5>
       <h6 class="card-subtitle mb-2 text-muted small pt-2">
        Duration: <%= @exercise.duration %>  Mood: <%= @exercise.mood %>
        <br>
        Status: <%= @exercise.status %>
      </h6>
      <div class="col-12 col-sm-12 p-0">
      <%= link_to 'Edit', edit_activity_path(@exercise), class: "card-link" %>
          <a class="card-link text-danger pointer" data-toggle="modal" data-target="#exampleModal" data-delete='<%= link_to 'Yes, Delete', delete_activity_path(@exercise), method: :delete, class: "btn btn-danger"%>'>Delete</a>
          <p class="pt-4"> <%= link_to 'Back to Profile', profile_path, class: "btn-link" %></p>
      </div>
    </div>
  </div>
</div>
</section>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">Alert</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <p class="modal-btn m-0"></p>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->

app/views/activities/timer.html.erb
<section>
  <div class="jumbotron jumbotron-fluid bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 text-left text-white montserrat py-1">
          <h1 class="display-4 font-weight-bold text-center">StopWatch</h1>
        </div>
      </div>
    </div>
  </div>
</section>


<section>
  <div class="container pb-8 mb-8">
    <div class="row">
      <div class="col-12 pt-4 text-center">
       <div id="chronoExample">
        <div class="values txt-50 txt-md-50 pb-5">00:00:00:00</div>
        <div>
        <button class="startButton btn btn-success">Start</button>
          <button class="pauseButton btn btn-primary">Pause</button>
          <button class="stopButton btn btn-danger" style="display:none;">Stop</button>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Move and Groove</title>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= javascript_include_tag 'application' %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" type="text/css" href="/css/designplate.css">
  <!-- Font Awesome Icons -->
  <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>
  <!--Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,800" rel="stylesheet">
  <link rel="icon" href="/moveandgroove.ico"/>
  <style>
    .form-group>span, .star {
      color: red;
    }
    .custom-control-input { z-index: 9000; }
  </style>
</head>

<body class="open-sans">

  <%= render "layouts/partials/msg" %>

  <%= render "layouts/partials/nav" %>

  <%= yield %>
  
  <% if current_page?(root_path) || current_page?(about_path) %>
  <%= render "layouts/partials/footer" %>
  <% end %>

</body>
<script
src="https://code.jquery.com/jquery-3.3.1.min.js"
integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
crossorigin="anonymous"></script> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="/js/easytimer.min.js"></script>
<script src="/js/main.js"></script>
</html>

app/views/layouts/partials/_footer.html.erb
<footer>
    <div class="container-fluid bg-gray1" >
      <div class="row">
        <div class="col-12 text-center">
          <p class="font-weight-bold txt-20 py-2 mb-0">Move and Grove</p>
        </div>
      </div>
    </div>
    <div class="container-fluid bg-gray2">
      <div class="row">
        <div class="col-12 text-center">
          <ul class="list-inline text-primary pt-4">
            <li class="list-inline-item"><%= link_to 'About Us', about_path %></li>|
            <li class="list-inline-item">Contact Us</li>|
            <% if !current_user %>
            <li class="list-inline-item"><%= link_to 'Sign In', new_user_session_path %></li>|
            <li class="list-inline-item"><%= link_to 'Sign Up', new_user_registration_path %></li>|
            <% end %>
            <li class="list-inline-item">Privacy Policy</li>
          </ul>
          <p class="small">Copyright 2018</p>
        </div>
      </div>
    </div>
  </footer>

app/views/layouts/partials/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light border-bottom">
  <div class="container">
    <% if !current_user %>
    <%= link_to 'Move and Groove', root_path, class: "navbar-brand font-weight-bold d-none d-sm-block" %>
    <a href="/" class="navbar-brand font-weight-bold  d-block d-sm-none">
      <img src="/img/moveandgroove.png" alt="moove and groove" class="img-fluid" style="width:60px;">
    </a>
    <% else %>
    <%= link_to 'Move and Groove', profile_path, class: "navbar-brand font-weight-bold d-none d-sm-block" %>
    <a href="/activity/profile" class="navbar-brand font-weight-bold  d-block d-sm-none">
      <img src="/img/moveandgroove.png" alt="moove and groove" class="img-fluid" style="width:60px;">
    </a>
    <% end %>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent2" aria-controls="navbarSupportedContent2" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse-v2 bg-white pb-2" id="navbarSupportedContent2">
    <div class="mobile-menu-container text-center text-lg-right">
      <a  data-target="#navbarSupportedContent2" class="menu-closebtn pointer pt-2 pr-4 txt-40">
        &times
      </a>
      <ul class="navbar-nav mobile-nav-v2 ml-auto w-100 w-lg-50 float-lg-right pb-0">
        <% if current_user %>
        <li class="nav-item ml-0 ml-lg-auto <%= current_page?(profile_path) ? 'active' : '' %>">
          <%= link_to 'Profile', profile_path , class: "nav-link" %>
        </li>
        <li class="nav-item <%= current_page?(activities_path) ? 'active' : '' %>">
          <%= link_to 'Activities', activities_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= current_page?(activities_path) ? 'active' : '' %>">
          <%= link_to 'StopWatch', timer_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete, class: "nav-link" %>
        </li>
        <% else %>
        <li class="nav-item ml-0 ml-lg-auto <%= current_page?(root_path) ? 'active' : '' %>">
          <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= current_page?(about_path) ? 'active' : '' %>">
          <%= link_to 'About', about_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= current_page?(new_user_registration_path) ? 'active' : '' %>">
          <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
         <%= link_to 'Sign In', new_user_session_path, class: "btn btn-primary mx-2 mt-lg-1 mb-lg-0 my-3 font-weight-bold" %>
       </li>
       <% end %>
     </ul>
   </div>
 </div>
</div>
</nav>

app/views/pages/index.html.erb
<section>
  <div class="jumbotron jumbotron-fluid bg-img" style="background-image: url(/img/run.jpg);background-position: 50% 100%;">
    <div class="container">
      <div class="row">
        <div class="col-sm-7 text-white montserrat  pt-8 pb-10 my-6">
          <h1 class="display-4 font-weight-bold">Workouts for every fitness level</h1>
          <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
          <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success btn-lg" %>
          <%= link_to 'Learn More', about_path, class: "btn btn-default btn-lg text-black" %>
        </div>
      </div>
    </div>
  </div>
</section>


<section>
  <div class="container">
    <div class="row">
      <div class="col-12 text-center py-6 mb-5">
        <h1>Millions of people have lost weight with <b>Move and Groove</b></h1>
        <h4>Get free access to this awesome app and don't miss out</h4>
      </div>
    </div>
  </div>
</section>